a = 5
b = 6  
print(f'{a} = {bin(a)}')
print(f'{b} = {bin(b)}')
print(f'{a} & {b} = {a & b}; {bin(a&b)}')
print(f'{a} | {b} = {a | b}; {bin(a|b)}')
print(f'{a} ^ {b} = {a ^ b}; {bin(a^b)}')
print(f'{a} << 2 = {a << 2}; {bin(a<<2)}')
print(f'{a} >> 2 = {a >> 2}; {bin(a>>2)}')
print(f'{b} << 2 = {b << 2}; {bin(b<<2)}')
print(f'{b} >> 2 = {b >> 2}; {bin(b>>2)}')
print(f'~{a}  = {~ a }; {bin(~a)}')
print(f'~{b}  = {~ b }; {bin(~b)}')
